// Generated by Xata Codegen 0.29.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "projects",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "N/A" },
    ],
  },
  {
    name: "projects_tags",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: " " },
      { name: "project_id", type: "string", notNull: true, defaultValue: " " },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Projects = InferredTypes["projects"];
export type ProjectsRecord = Projects & XataRecord;

export type ProjectsTags = InferredTypes["projects_tags"];
export type ProjectsTagsRecord = ProjectsTags & XataRecord;

export type DatabaseSchema = {
  projects: ProjectsRecord;
  projects_tags: ProjectsTagsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://endydev-s-workspace-m6g31i.us-east-1.xata.sh/db/portfolio",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient({
    apiKey: import.meta.env.XATA_API_KEY,
    branch: import.meta.env.XATA_BRANCH
  });
  return instance;
};
